module ChatApp {
   interface ChatCallback {
      void callback(in string message);
   };
   interface Chat {
      void post(in ChatCallback cc, in string message);
      void join(in ChatCallback cc, in string name);
      void leave(in ChatCallback cc);
      void list(in ChatCallback cc);
      void game(in ChatCallback cc, in string marker);
      void place(in ChatCallback cc, in string coords);
   };
};
